### ISSUE TITLE
As a stubserver user I want to be able to programatically define the behavior of a stub

### ISSUE THREAD

**Issue by jordi133** [scala-academy/castalia#10]
background:
given that the stubserver is started and configured to use a stub called "programmedstub"
and that a stub config file with name "programmedstub.json" is on the classpath
and "programmedstub.json" contains a property "endpoint" equal to "programmedstub"

given that "programmedstub.json" contains a property "behaviorSource" equal to "ProgrammedStub.class"
and "ProgrammedStub.class" is on the classpath
when I do a HTTP GET to .../castalia/stubs/programmedstub/<anyId>
then the logic programmed in ProgrammedStub.scala should be used for creating the response

**Comment by rezolya** [comment]
can you add an example of ProgrammedStub.scala?

**Comment by rezolya** [comment]
do we need to compile the file ourselves, or do we get a jar?

**Comment by rezolya** [comment]
does the ProgrammedStub.scala contain Main object? does it take any parameters? how do we know which method to execute?

**Comment by rezolya** [comment]
Is the program  supposed to return a json content or send the reply to the requester already?

**Comment by jordi133** [comment]
Let's assume that there is a .class file (for example ProgrammedStub.class) available on the classpath of castalia and that the stub config contains "source" = "ProgrammedStub"

**Comment by jeanmarc** [comment]
There should be a  trait that mixes in a function process(httpRequest: HttpRequest): StubResponse (or a RequestMatch, which will be enriched with the httpRequest.
