### ISSUE TITLE
As a stubserver consumer I want to be able to specify which stub config files should be used by the server in the server configuration file

### ISSUE THREAD

**Issue by jordi133** [scala-academy/castalia#22]
given that a stubserver config file with name "castalia.json" is on the classpath
and "castalia.json" contains a property "stubs" with value ["stub1.json", "stub2.json"]
and files "stub1.json" and "stub2.json" are both on the classpath
when I do a HTTP GET to the endpoint as configured in "stub1.json"
then the response should be as configured in "stub1.json"

given that a stubserver config file with name "castalia.json" is on the classpath
and "castalia.json" contains a property "stubs" with value ["stub1.json", "stub2.json"]
and files "stub1.json" and "stub2.json" are both on the classpath
when I do a HTTP GET to the endpoint as configured in "stub2.json"
then the response should be as configured in "stub2.json"

given that a stubserver config file with name "castalia.json" is on the classpath
and "castalia.json" contains a property "stubs" with value ["stub1.json", "stub2.json"]
and both "stub1.json" and "stub2.json" define the same endpoint
when the stubserver is started with command line argument "stub1.json stub2.json"
then the stubserver should not start successfully, giving a meaningful error message

**Comment by effibennekers** [comment]
do you want to give an example castalia.json? These are really useful.

**Comment by erik121212** [comment]
Example castalia.json:

{
  "httpPort": 9000,
  "stubs": ["jsonconfiguredstub.json", "someotherjsonfile.json"]
}
