### ISSUE TITLE
As a stubserver consumer I want to be able to specify the endpoint of a stub in a separate json file

### ISSUE THREAD

**Issue by jordi133** [scala-academy/castalia#7]
Acceptance criteria:

background:
given that the stubserver is started and configured to use a stub called "jsonconfiguredstub"
and that a stub config file with name "jsonconfiguredstub.json" is on the classpath

given that jsonconfiguredstub.json contains a property "endpoint" equal to "jsonconfiguredstub"
when I do a HTTP GET to .../castalia/stubs/jsonconfiguredstub
then I should get a HTTP 200 response

**Comment by TimSoethout** [comment]
example branch name: `feature/#7-endpoint-in-json`
