### ISSUE TITLE
As a stubserver consumer I want to be able to define the latency of a stub in the stub config file

### ISSUE THREAD

**Issue by jordi133** [scala-academy/castalia#9]
Acceptance criteria:

background:
given that the stubserver is started and configured to use a stub called "latencystub"
and that a stub config file with name "latencystub.json" is on the classpath

given that latencystub.json contains a response with property "id" equal to "{stubId}" and a delay specified as always 100 ms
when I do a HTTP GET to .../castalia/stubs/latencystub/{stubId}
then after roughly 100 ms I should get a HTTP 200 response containing the stub response with id "{stubId}"

given that latencystub.json contains a response with property "id" equal to "{stubId}" and not a property "delay"
when I do a HTTP GET to .../castalia/stubs/latencystub/{stubId}
then I should get a HTTP 200 response containing the stub response with id "{stubId}" without any significant latency (faster than 10 ms)

**Comment by jordi133** [comment]
Example json:

{
  "endpoint": "jsonconfiguredstub",
  "responses": [
    { 
      "id": "1",
      "delay": {
        "distribution": "constant",
        "mean": "100 ms"
      },
      "httpStatusCode": 200,
      "response": {
        "id": "een",
        "someValue": "123123"
      }
    },
    { 
      "id": "2",
      "httpStatusCode": 200,
      "response": {
        "id": "twee",
        "someValue": "123123",
        "someAdditionalValue": "345345"
      }
    },
    { 
      "id": "0",
      "delay": {
        "distribution": "constant",
        "mean": "2 s"
      },
      "httpStatusCode": 404
    }
  ]
}

**Comment by effibennekers** [comment]
Are "ms" and "s" good unit decriptors? I would prefer a Java duration (ie 100 millis, 2 seconds)

**Comment by DieBauer** [comment]
Aangepaste future van spray utils met delay functie: https://github.com/spray/spray/blob/master/spray-util/src/main/scala/spray/util/pimps/PimpedFuture.scala

**Comment by DieBauer** [comment]
Proposal: Make "mean" an int in milliseconds. => "mean": 2000 instead of "mean": "2 s". This is less error-prone.  And it is still clear what is meant.
